[package]
name = "ipw-embedded"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embassy-embedded-hal = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt"] }
embassy-sync = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt"] }
embassy-executor = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["task-arena-size-98304", "arch-cortex-m", "executor-thread", "executor-interrupt", "defmt", "integrated-timers"] }
embassy-time = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt", "defmt-timestamp-uptime"] }
embassy-rp = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt", "unstable-pac", "time-driver", "critical-section-impl"] }
embassy-usb = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt"] }
embassy-net = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt", "tcp", "udp", "raw", "dhcpv4", "medium-ethernet", "dns"] }
embassy-net-wiznet = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt"] }
embassy-futures = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6" }
embassy-usb-logger = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6" }

cyw43 = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt", "firmware-logs"] }
cyw43-pio = { git = "https://github.com/embassy-rs/embassy.git", rev = "fdc34b6", features = ["defmt"] }

defmt = "0.3"
defmt-rtt = "0.4"
fixed = "1.23.1"
fixed-macro = "1.2"

cortex-m = { version = "0.7.6", features = ["inline-asm"] }
cortex-m-rt = "0.7.0"
critical-section = "1.1"
panic-probe = { version = "0.3", features = ["print-defmt"] }
display-interface-spi = "0.4.1"
embedded-graphics = "0.7.1"
st7789 = "0.6.1"
display-interface = "0.4.1"
byte-slice-cast = { version = "1.2.0", default-features = false }
smart-leds = "0.3.0"
heapless = "0.8"
usbd-hid = "0.8.1"

embedded-hal-1 = { package = "embedded-hal", version = "1.0" }
embedded-hal-async = "1.0"
embedded-hal-bus = { version = "0.1", features = ["async"] }
embedded-io-async = { version = "0.6.1", features = ["defmt-03"] }
embedded-storage = { version = "0.3" }
static_cell = "2"
portable-atomic = { version = "1.5", features = ["critical-section"] }
log = "0.4"
pio-proc = "0.2"
pio = "0.2.1"
rand = { version = "0.8.5", default-features = false }
embedded-sdmmc = "0.7.0"

[profile.release]
debug = 2
lto = true
opt-level = 'z'

[profile.dev]
debug = 2
lto = true
opt-level = "z"

# Binary list
# Here you will have to add your binaries

[[bin]]
name = "blinky"
path = "src/demo/exercise6.rs"

# [[bin]]
# name = "my_bin"
# path = "path/to/my/bin"
